version: 2.1

orbs:
  v8: "twuni/nodejs@8.16.0"
  v10: "twuni/nodejs@10.15.3"
  v11: "twuni/nodejs@11.15.0"
  v12: "twuni/nodejs@12.1.0"

workflows:
  v8:
    jobs:
    - v8/initialize
    - v8/install:
        requires:
        - v8/initialize
    - v8/style:
        requires:
        - v8/install
    - v8/build:
        requires:
        - v8/install
    - v8/test:
        requires:
        - v8/install
  v10:
    jobs:
    - v10/initialize
    - v10/install:
        requires:
        - v10/initialize
    - v10/style:
        requires:
        - v10/install
    - v10/build:
        requires:
        - v10/install
    - v10/test:
        requires:
        - v10/install
  v11:
    jobs:
    - v11/initialize
    - v11/install:
        requires:
        - v11/initialize
    - v11/style:
        requires:
        - v11/install
    - v11/build:
        requires:
        - v11/install
    - v11/test:
        requires:
        - v11/install
  v12:
    jobs:
    - v12/initialize
    - v12/install:
        requires:
        - v12/initialize
    - v12/style:
        requires:
        - v12/install
    - v12/build:
        requires:
        - v12/install
    - v12/test:
        requires:
        - v12/install
